kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarbdialog
  namespace: {{namespace}}
  cluster: dev-fss
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/veilarbdialog/veilarbdialog:{{version}}
  ingresses:
    - https://veilarbdialog-{{namespace}}.nais.preprod.local
    - https://app-{{namespace}}.adeo.no/veilarbdialog
  port: 8080
  prometheus:
    enabled: true
    path: /veilarbdialog/internal/prometheus
  liveness:
    path: /veilarbdialog/internal/info
    port: 8080
    initialDelay: 60
  readiness:
    path: /veilarbdialog/internal/info
    port: 8080
    initialDelay: 60
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "2"
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 768Mi
  envFrom:
    - configmap: pto-config
    - configmap: loginservice-idporten
  vault:
    enabled: true
    paths:
      - kvPath: /oracle/data/dev/creds/veilarbdialog_{{namespace}}-user
        mountPath: /var/run/secrets/nais.io/oracle_creds
      - kvPath: /oracle/data/dev/config/veilarbdialog_{{namespace}}
        mountPath: /var/run/secrets/nais.io/oracle_config
      - kvPath: /serviceuser/data/dev/srvveilarbdialog
        mountPath: /secrets/serviceuser
      - kvPath: /kv/preprod/fss/veilarbdialog/{{namespace}}
        mountPath: /var/run/secrets/nais.io/vault
  webproxy: true
  env:
    - name: APP_ENVIRONMENT_NAME
      value: {{namespace}}
    - name: APP_CLUSTER_NAME
      value: dev-fss
