kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarbdialog
  namespace: pto
  cluster: prod-fss
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/veilarbdialog/veilarbdialog:{{version}}
  port: 8080
  prometheus:
    enabled: true
    path: /veilarbdialog/internal/prometheus
  liveness:
    path: /veilarbdialog/internal/info
    port: 8080
    initialDelay: 30
  readiness:
    path: /veilarbdialog/internal/info
    port: 8080
    initialDelay: 30
  replicas:
    min: 4
    max: 8
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "2"
      memory: 8092Mi
    requests:
      cpu: "1"
      memory: 1536Mi
  ingresses:
    - https://veilarbdialog.nais.adeo.no
    - https://app.adeo.no/veilarbdialog
  envFrom:
    - configmap: pto-config
    - configmap: loginservice-idporten
  vault:
    enabled: true
    paths:
      - kvPath: /oracle/data/prod/creds/veilarbdialog-user
        mountPath: /var/run/secrets/nais.io/oracle_creds
      - kvPath: /oracle/data/prod/config/veilarbdialog
        mountPath: /var/run/secrets/nais.io/oracle_config
      - kvPath: /serviceuser/data/prod/srvveilarbdialog
        mountPath: /secrets/serviceuser
      - kvPath: /kv/prod/fss/veilarbdialog/default
        mountPath: /var/run/secrets/nais.io/vault
  webproxy: true
  secureLogs:
    enabled: true
  env:
    - name: APP_ENVIRONMENT_NAME
      value: p
    - name: APP_CLUSTER_NAME
      value: prod-fss
    - name: ENDRING_PAA_DIALOG_TOPIC
      value: aapen-fo-endringPaaDialog-v1-p
    - name: OPPFOLGING_AVSLUTTET_TOPIC
      value: aapen-arbeidsrettetOppfolging-oppfolgingAvsluttet-v1-p
    - name: KVP_AVSLUTTET_TOPIC
      value: aapen-arbeidsrettetOppfolging-kvpAvsluttet-v1-p
