kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarbdialog
  namespace: pto
  cluster: dev-fss
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/veilarbdialog/veilarbdialog:{{version}}
  ingresses:
    - https://veilarbdialog-q1.nais.preprod.local
    - https://app-q1.adeo.no/veilarbdialog
    - https://app-q1.dev.adeo.no/veilarbdialog
  port: 8080
  prometheus:
    enabled: true
    path: /veilarbdialog/internal/prometheus
  liveness:
    path: /veilarbdialog/internal/info
    port: 8080
    initialDelay: 30
  readiness:
    path: /veilarbdialog/internal/info
    port: 8080
    initialDelay: 30
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "2"
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 768Mi
  envFrom:
    - configmap: pto-config
    - configmap: loginservice-idporten
  vault:
    enabled: true
    paths:
      - kvPath: /oracle/data/dev/creds/veilarbdialog_q1-user
        mountPath: /var/run/secrets/nais.io/oracle_creds
      - kvPath: /oracle/data/dev/config/veilarbdialog_q1
        mountPath: /var/run/secrets/nais.io/oracle_config
      - kvPath: /serviceuser/data/dev/srvveilarbdialog
        mountPath: /secrets/serviceuser
      - kvPath: /kv/preprod/fss/veilarbdialog/q1
        mountPath: /var/run/secrets/nais.io/vault
  webproxy: true
  env:
    - name: APP_ENVIRONMENT_NAME
      value: q1
    - name: APP_CLUSTER_NAME
      value: dev-fss
    - name: ENDRING_PAA_DIALOG_TOPIC
      value: aapen-fo-endringPaaDialog-v1-q1
    - name: OPPFOLGING_AVSLUTTET_TOPIC
      value: aapen-arbeidsrettetOppfolging-oppfolgingAvsluttet-v1-q1
    - name: KVP_AVSLUTTET_TOPIC
      value: aapen-arbeidsrettetOppfolging-kvpAvsluttet-v1-q1