CREATE TABLE DIALOG_EGENSKAP_TYPE (
  DIALOG_TYPE    VARCHAR(255)   NOT NULL
    CONSTRAINT DIALOG_EGENSKAP_TYPE_PK PRIMARY KEY,
  OPPRETTET_DATO TIMESTAMP(6)   NOT NULL,
  OPPRETTET_AV   NVARCHAR2(255) NOT NULL,
  ENDRET_DATO    TIMESTAMP(6)   NOT NULL,
  ENDRET_AV      NVARCHAR2(255) NOT NULL
);

INSERT INTO DIALOG_EGENSKAP_TYPE(
  DIALOG_TYPE, OPPRETTET_DATO, OPPRETTET_AV, ENDRET_DATO, ENDRET_AV
) VALUES ('ESKALERINGSVARSEL',CURRENT_TIMESTAMP,'***REMOVED***',CURRENT_TIMESTAMP,'***REMOVED***');


CREATE TABLE DIALOG_EGENSKAP (
  DIALOG_EGENSKAP_TYPE_KODE VARCHAR(255) NOT NULL CONSTRAINT DIALOG_EGENSKAP_TYPE_FK
  REFERENCES DIALOG_EGENSKAP_TYPE(DIALOG_TYPE),
  DIALOG_ID NUMBER NOT NULL CONSTRAINT DIALOG_FK REFERENCES DIALOG(DIALOG_ID)
);

