CREATE SEQUENCE HENVENDELSE_ID_SEQ START WITH 1 INCREMENT BY 1;
TRUNCATE TABLE HENVENDELSE;
ALTER TABLE HENVENDELSE ADD henvendelse_id number(19, 0) not null;
ALTER TABLE HENVENDELSE ADD CONSTRAINT henvendelse_pk primary key(henvendelse_id);