CREATE TABLE EVENT_TYPE (
  event NVARCHAR2(255) NOT NULL,
  CONSTRAINT EVENT_TYPE_PK PRIMARY KEY (event)
);

CREATE TABLE EVENT (
  event_id    NUMBER(19)    NOT NULL,
  dialogid    NUMBER(19)    NOT NULL,
  event       NVARCHAR2(255) NOT NULL,
  tidspunkt   TIMESTAMP,
  aktor_id      NVARCHAR2(255),
  aktivitet_id NVARCHAR2(255),
  CONSTRAINT EVENT_PK PRIMARY KEY (event_id),
  CONSTRAINT EVENT_EVENT_TYPE_FK FOREIGN KEY (event) REFERENCES EVENT_TYPE (event)
);

CREATE SEQUENCE EVENT_ID_SEQ
  START WITH 1
  INCREMENT BY 1;

INSERT INTO EVENT_TYPE VALUES ('DIALOG_OPPRETTET');
INSERT INTO EVENT_TYPE VALUES ('NY_HENVENDELSE_FRA_BRUKER');
INSERT INTO EVENT_TYPE VALUES ('NY_HENVENDELSE_FRA_VEILEDER');
INSERT INTO EVENT_TYPE VALUES ('VENTER_PAA_NAV');
INSERT INTO EVENT_TYPE VALUES ('BESVART_AV_NAV');
INSERT INTO EVENT_TYPE VALUES ('VENTER_PAA_BRUKER');
INSERT INTO EVENT_TYPE VALUES ('BESVART_AV_BRUKER');
INSERT INTO EVENT_TYPE VALUES ('LEST_AV_VEILEDER');
INSERT INTO EVENT_TYPE VALUES ('LEST_AV_BRUKER');
INSERT INTO EVENT_TYPE VALUES ('SATT_TIL_HISTORISK');

CREATE VIEW DVH_Dialog_hendelse AS
  SELECT
    event_id,
    dialogid,
    event,
    tidspunkt,
    aktor_id,
    aktivitet_id
  FROM EVENT;

CREATE VIEW DVH_Dialog_hendelse_type AS
  SELECT event
  FROM EVENT_TYPE;