ALTER TABLE DIALOG DROP COLUMN SISTE_STATUS_ENDRING;
ALTER TABLE DIALOG DROP COLUMN SISTE_VENTE_PA_SVAR_TID;
ALTER TABLE DIALOG DROP COLUMN SISTE_FERDIGBEHANDLET_TID;
ALTER TABLE DIALOG DROP COLUMN SISTE_UBEHANDLET_TID;