apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: veilarbdialog-low-priority-alarm
  namespace: pto
  labels:
    team: pto
spec:
  receivers:
    slack:
      channel: '#team_dab_alerts'
    route:
      repeatInterval: 24h
  alerts:
    - alert: Vedvarende feilrate i veilarbdialog
      expr: |
        (((
        sum(rate(traefik_backend_requests_total{backend=~"^app.adeo.no/veilarbdialog|^veilarbdialog.nais.adeo.no/",protocol="http",code!~'(^[23].*)'}[24h]    )  )  /
        sum(rate(traefik_backend_requests_total{backend=~"^app.adeo.no/veilarbdialog|^veilarbdialog.nais.adeo.no/",protocol="http"}[24h]    )    ) )  > (3*0.001) )
        and  ((
        sum(rate(traefik_backend_requests_total{backend=~"^app.adeo.no/veilarbdialog|^veilarbdialog.nais.adeo.no/",protocol="http",code!~'(^[23].*)'}[2h]    )  )  /
        sum(rate(traefik_backend_requests_total{backend=~"^app.adeo.no/veilarbdialog|^veilarbdialog.nais.adeo.no/",protocol="http"}[2h]    )    ) )  > (3*0.001) 
            and ( hour(vector(time())) >= 06 and hour(vector(time())) <= 23 
        )))
      for: 8h
      severity: warning
      description: Vedvarende 500 feilrate i veilarbdialog
      action: https://logs.adeo.no/goto/3e24330cd8dbe344a1b5d0c4e1cb4d48  https://grafana.nais.io/d/000000283/nais-app-dashbord?orgId=1&var-interval=$__auto_interval_interval&var-datasource=prod-fss&var-team=pto&var-app=veilarbdialog&var-namespace=All&var-docker_image=5e399fce17a0617acda62a3b4c969210d05abc17&var-ingress_url=All&from=now-4d&to=now
      sla: se på denne i løpet av de neste dagene.
    - alert: Vedvarende feilrate i veilarbdialog
      expr: |
        ( (   (
        sum(rate(traefik_backend_requests_total{backend=~"^app.adeo.no/veilarbdialog|^veilarbdialog.nais.adeo.no/",protocol="http",code!~'(^[234].*)'}[3d]    )  )  /
        sum(rate(traefik_backend_requests_total{backend=~"^app.adeo.no/veilarbdialog|^veilarbdialog.nais.adeo.no/",protocol="http"}[3d]    )    ) )  > 0.001 )
        and  (  (
        sum(rate(traefik_backend_requests_total{backend=~"^app.adeo.no/veilarbdialog|^veilarbdialog.nais.adeo.no/",protocol="http",code!~'(^[234].*)'}[6h]    )  )  /
        sum(rate(traefik_backend_requests_total{backend=~"^app.adeo.no/veilarbdialog|^veilarbdialog.nais.adeo.no/",protocol="http"}[6h]    )    ) )  > 0.001 ) )
      for: 8h
      severity: warning
      description: Vedvarende 500 feilrate i veilarbdialog
      action: https://logs.adeo.no/goto/3e24330cd8dbe344a1b5d0c4e1cb4d48  https://grafana.nais.io/d/000000283/nais-app-dashbord?orgId=1&var-interval=$__auto_interval_interval&var-datasource=prod-fss&var-team=pto&var-app=veilarbdialog&var-namespace=All&var-docker_image=5e399fce17a0617acda62a3b4c969210d05abc17&var-ingress_url=All&from=now-4d&to=now
      sla: se på denne i løpet av de neste dagene.
 