apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: veilarbdialog-alarm
  namespace: pto
  labels:
    team: pto
spec:
  receivers:
    slack:
      channel: '#team_dab_alerts'
      prependText: '<!here> | '
  alerts:
    - alert: Høy feilrate veilarbdialog dagtid
      expr: |
        ((((
        sum(rate(traefik_backend_requests_total{backend=~"^app.adeo.no/veilarbdialog|^veilarbdialog.nais.adeo.no/",protocol="http",code!~'(^[23].*)'}[5m] ) ) /
        sum(rate(traefik_backend_requests_total{backend=~"^app.adeo.no/veilarbdialog|^veilarbdialog.nais.adeo.no/",protocol="http"}[5m]) ) )  > (14.4*0.001))
        and ( (
        sum(rate(traefik_backend_requests_total{backend=~"^app.adeo.no/veilarbdialog|^veilarbdialog.nais.adeo.no/",protocol="http",code!~'(^[23].*)'}[1h] ) ) /
        sum(rate(traefik_backend_requests_total{backend=~"^app.adeo.no/veilarbdialog|^veilarbdialog.nais.adeo.no/",protocol="http"}[1h] ) ) )  > (14.4*0.001) ))
        or ( ( (
        sum(rate(traefik_backend_requests_total{backend=~"^app.adeo.no/veilarbdialog|^veilarbdialog.nais.adeo.no/",protocol="http",code!~'(^[23].*)'}[30m] ) ) /
        sum(rate(traefik_backend_requests_total{backend=~"^app.adeo.no/veilarbdialog|^veilarbdialog.nais.adeo.no/",protocol="http"}[30m] ) ) )  > (6*0.001) )
        and ( (
        sum(rate(traefik_backend_requests_total{backend=~"^app.adeo.no/veilarbdialog|^veilarbdialog.nais.adeo.no/",protocol="http",code!~'(^[23].*)'}[6h] ) ) /
        sum(rate(traefik_backend_requests_total{backend=~"^app.adeo.no/veilarbdialog|^veilarbdialog.nais.adeo.no/",protocol="http"}[6h] ) ) )  > (6*0.001))))        
        and ( hour(vector(time())) >= 06 and hour(vector(time())) <= 23 )
      for: 1m
      severity: danger
      description: Høy feilrate mot veilarbdialog.
      action: https://logs.adeo.no/goto/3e24330cd8dbe344a1b5d0c4e1cb4d48   https://grefana.nais.io/d/000000283/nais-app-dashbord?orgId=1&var-interval=$__auto_interval_interval&var-datasource=prod-fss&var-team=pto&var-app=veilarbdialog&var-namespace=All&var-docker_image=5e399fce17a0617acda62a3b4c969210d05abc17&var-ingress_url=All&from=now-6h&to=now
      sla: se på denne så fort som mulig (innefor arbeidstid)
    - alert: feil ved deploy?
      expr: 'kube_deployment_status_replicas_unavailable{deployment="veilarbdialog"} > 0'
      for: 10m
      action: https://logs.adeo.no/goto/6fc98f8662b9893c80c103ba3a30fbfa
      description: feilet deploy?
      severity: warning
    - alert: Feil med ekstern varsel kvitering
      expr: 'max(brukernotifikasjon_mangler_kvittering{application="veilarbdialog"}) > 0.8'
      for: 10m
      action: https://logs.adeo.no/goto/6fc98f8662b9893c80c103ba3a30fbfa
      description: forskinget kvitering på externvarsel
      severity: warning
    - alert: applikasjon nede
      expr: kube_deployment_status_replicas_available{deployment="veilarbdialog"} == 0
      for: 2m
      description: "App {{ $labels.app }} er nede i namespace {{ $labels.kubernetes_namespace }}"
      action: "`kubectl describe pod -l app={{ $labels.app }} -n {{ $labels.namespace }}` for events, og `kubectl logs -l app={{ $labels.app }} -n {{ $labels.namespace }}` for logger"
    - alert: høy feilrate i logger
      expr: (100 * sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="veilarbdialog",log_level=~"Warning|Error"}[3m])) / sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="veilarbdialog"}[3m]))) > 10
      for: 3m
      action: "Sjekk loggene til app {{ $labels.log_app }} i namespace {{ $labels.log_namespace }}, for å se hvorfor det er så mye feil"
    - alert: feil i selftest
      expr: selftests_aggregate_result_status{app="veilarbdialog"} > 0
      for: 1m
      action: "Sjekk app {{ $labels.app }} i namespace {{ $labels.kubernetes_namespace }} sine selftest for å se hva som er galt"

 