apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: veilarbdialog-low-priority-alarm
  namespace: pto
  labels:
    team: pto
spec:
  receivers:
    slack:
      channel: '#team_dab_alerts_dev'
    route:
      repeatInterval: 24h
  alerts:
    - alert: Vedvarende feilrate i veilarbdialog
      expr: |
        (((
        sum(rate(traefik_backend_requests_total{backend=~"^app-q1.adeo.no/veilarbdialog|veilarbdialog.nais.adeo.no/|^app-q1.dev.adeo.no/veilarbdialog",protocol="http",code!~'(^[23].*)'}[24h]    )  )  /
        sum(rate(traefik_backend_requests_total{backend=~"^app-q1.adeo.no/veilarbdialog|veilarbdialog.nais.adeo.no/|^app-q1.dev.adeo.no/veilarbdialog",protocol="http"}[24h]    )    ) )  > (3*0.001) )
        and  (  (
        sum(rate(traefik_backend_requests_total{backend=~"^app-q1.adeo.no/veilarbdialog|veilarbdialog.nais.adeo.no/|^app-q1.dev.adeo.no/veilarbdialog",protocol="http",code!~'(^[23].*)'}[2h]    )  )  /
        sum(rate(traefik_backend_requests_total{backend=~"^app-q1.adeo.no/veilarbdialog|veilarbdialog.nais.adeo.no/|^app-q1.dev.adeo.no/veilarbdialog",protocol="http"}[2h]    )    ) )  > (3*0.001) ) )
        or ( (   (
        sum(rate(traefik_backend_requests_total{backend=~"^app-q1.adeo.no/veilarbdialog|veilarbdialog.nais.adeo.no/|^app-q1.dev.adeo.no/veilarbdialog",protocol="http",code!~'(^[23].*)'}[3d]    )  )  /
        sum(rate(traefik_backend_requests_total{backend=~"^app-q1.adeo.no/veilarbdialog|veilarbdialog.nais.adeo.no/|^app-q1.dev.adeo.no/veilarbdialog",protocol="http"}[3d]    )    ) )  > 0.001 )
        and  (  (
        sum(rate(traefik_backend_requests_total{backend=~"^app-q1.adeo.no/veilarbdialog|veilarbdialog.nais.adeo.no/|^app-q1.dev.adeo.no/veilarbdialog",protocol="http",code!~'(^[23].*)'}[6h]    )  )  /
        sum(rate(traefik_backend_requests_total{backend=~"^app-q1.adeo.no/veilarbdialog|veilarbdialog.nais.adeo.no/|^app-q1.dev.adeo.no/veilarbdialog",protocol="http"}[6h]    )    ) )  > 0.001 ) )
      for: 8h
      severity: warning
      description: Vedvarende feilrate i veilarbdialog
      action: https://grefana.nais.io/d/z4LNWq-Mz/dab-alarmer \n https://logs.adeo.no/goto/cdf0a76551d4f4731d872ef702d60ff6
      sla: se på denne i løpet av de neste dagene.
 
