apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: veilarbdialog-alarm
  namespace: pto
  labels:
    team: pto
spec:
  receivers:
    slack:
      channel: '#team_dab_alerts_dev'
      prependText: ' '
  alerts:
    - alert: Høy feilrate veilarbdialog
      expr: |
        (((
        sum(rate(traefik_backend_requests_total{backend=~"^app-q1.adeo.no/veilarbdialog|veilarbdialog.nais.adeo.no/|^app-q1.dev.adeo.no/veilarbdialog",protocol="http",code!~'(^[23].*)'}[5m] ) ) /
        sum(rate(traefik_backend_requests_total{backend=~"^app-q1.adeo.no/veilarbdialog|veilarbdialog.nais.adeo.no/|^app-q1.dev.adeo.no/veilarbdialog",protocol="http"}[5m]) ) )  > (14.4*0.001) )
        and ( (
        sum(rate(traefik_backend_requests_total{backend=~"^app-q1.adeo.no/veilarbdialog|veilarbdialog.nais.adeo.no/|^app-q1.dev.adeo.no/veilarbdialog",protocol="http",code!~'(^[23].*)'}[1h] ) ) /
        sum(rate(traefik_backend_requests_total{backend=~"^app-q1.adeo.no/veilarbdialog|veilarbdialog.nais.adeo.no/|^app-q1.dev.adeo.no/veilarbdialog",protocol="http"}[1h] ) ) )  > (14.4*0.001) ))
        or ( ( (
        sum(rate(traefik_backend_requests_total{backend=~"^app-q1.adeo.no/veilarbdialog|veilarbdialog.nais.adeo.no/|^app-q1.dev.adeo.no/veilarbdialog",protocol="http",code!~'(^[23].*)'}[30m] ) ) /
        sum(rate(traefik_backend_requests_total{backend=~"^app-q1.adeo.no/veilarbdialog|veilarbdialog.nais.adeo.no/|^app-q1.dev.adeo.no/veilarbdialog",protocol="http"}[30m] ) ) )  > (6*0.001) )
        and ( (
        sum(rate(traefik_backend_requests_total{backend=~"^app-q1.adeo.no/veilarbdialog|veilarbdialog.nais.adeo.no/|^app-q1.dev.adeo.no/veilarbdialog",protocol="http",code!~'(^[23].*)'}[6h] ) ) /
        sum(rate(traefik_backend_requests_total{backend=~"^app-q1.adeo.no/veilarbdialog|veilarbdialog.nais.adeo.no/|^app-q1.dev.adeo.no/veilarbdialog",protocol="http"}[6h] ) ) )  > (6*0.001)))
      for: 1s
      severity: danger
      description: Høy feilrate mot veilarbdialog.
      action: https://grafana.nais.io/d/z4LNWq-Mz/dab-alarmer \n https://logs.adeo.no/goto/cdf0a76551d4f4731d872ef702d60ff6
      sla: se på denne så fort som mulig (innefor arbeidstid)