kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarbdialog
  namespace: dab
  labels:
    team: dab
  annotations:
    config.linkerd.io/proxy-cpu-limit: 500m
spec:
  image: {{image}}
  ingresses:
    - https://veilarbdialog.dev.nav.cloud.nais.io
    - https://veilarbdialog.intern.dev.nav.no
  port: 8080
  prometheus:
    enabled: true
    path: /veilarbdialog/internal/prometheus
  liveness:
    path: /veilarbdialog/internal/info
    port: 8080
    initialDelay: 30
  readiness:
    path: /veilarbdialog/internal/info
    port: 8080
    initialDelay: 30
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 768Mi
  envFrom:
    - secret: veilarbdialog-unleash-api-token
    - secret: veilarbdialog-kassering-identer
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  secureLogs:
    enabled: true
  kafka:
    pool: nav-dev
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    inbound:
      rules:
        - application: veilarbapi
          namespace: pto
          cluster: dev-gcp
        - application: arbeidssokerregistrering-for-veileder
          namespace: paw
          cluster: dev-gcp
        - application: veilarbpersonflate
          namespace: poao
          cluster: dev-gcp
        - application: mulighetsrommet-api
          namespace: team-mulighetsrommet
          cluster: dev-gcp
        - application: veilarbdirigent
          namespace: pto
          cluster: dev-fss
        - application: aktivitetsplan
          namespace: pto
          cluster: dev-gcp
        - application: arbeidsrettet-dialog
          namespace: pto
          cluster: dev-gcp
        - application: aia-backend
          namespace: paw
          cluster: dev-gcp
        - application: start-samtale
          namespace: pto
          cluster: dev-gcp
        - application: veilarbaktivitet
          namespace: dab
          cluster: dev-gcp
    outbound:
      external:
        - host: dab-unleash-api.nav.cloud.nais.io
        - host: pdl-api.dev-fss-pub.nais.io
      rules:
        - application: veilarboppfolging
          namespace: poao
        - application: poao-tilgang
          namespace: poao
        - application: please
          namespace: dab
  gcp:
    sqlInstances:
      - name: veilarbdialog
        type: POSTGRES_14
        tier: db-custom-1-3840
        diskType: SSD
        diskAutoresize: true
        flags: # Nødvendig for datastreams
          - name: cloudsql.logical_decoding
            value: "on"
          - name: log_statement
            value: "mod"
        databases:
          - name: veilarbdialog
            envVarPrefix: DB
            users:
              - name: datastream
    bigQueryDatasets:
      - description: Funksjonelle metrikker for arbeidsrettet dialog
        name: dialog_metrikker
        permission: READWRITE
  env:
    - name: APP_CLUSTER_NAME
      value: dev-gcp
    - name: DIALOG_EKSTERN_URL
      value: https://pto.ekstern.dev.nav.no/arbeid/dialog
    - name: POAO_TILGANG_SCOPE
      value: api://dev-gcp.poao.poao-tilgang/.default
    - name: POAO_TILGANG_URL
      value: http://poao-tilgang.poao
    - name: PDL_URL
      value: https://pdl-api.dev-fss-pub.nais.io
    - name: PLEASE_URL
      value: http://please
    - name: PLEASE_AZURE_SCOPE
      value: api://dev-gcp.dab.please/.default
    - name: PLEASE_TOKENX_SCOPE
      value: dev-gcp:dab:please
    - name: KAFKA_ENABLED
      value: "true"
    - name: VEILARBOPPFOLGINGAPI_URL
      value: "http://veilarboppfolging.poao"
    - name: VEILARBOPPFOLGINGAPI_AZURE_SCOPE
      value: api://dev-gcp.poao.veilarboppfolging/.default
    - name: VEILARBOPPFOLGINGAPI_TOKENX_SCOPE
      value: dev-gcp:poao:veilarboppfolging