kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarbdialog
  namespace: pto
  cluster: dev-fss
  labels:
    team: pto
spec:
  image: ghcr.io/navikt/veilarbdialog/veilarbdialog:{{version}}
  ingresses:
    - https://veilarbdialog-q1.nais.preprod.local
    - https://app-q1.adeo.no/veilarbdialog
    - https://app-q1.dev.adeo.no/veilarbdialog
    - https://app.dev.adeo.no/veilarbdialog
    - https://veilarbdialog.dev-fss-pub.nais.io
  port: 8080
  prometheus:
    enabled: true
    path: /veilarbdialog/internal/prometheus
  liveness:
    path: /veilarbdialog/internal/info
    port: 8080
    initialDelay: 30
  readiness:
    path: /veilarbdialog/internal/info
    port: 8080
    initialDelay: 30
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "2"
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 768Mi
  envFrom:
    - configmap: pto-config
    - configmap: loginservice-idporten
  vault:
    enabled: true
    paths:
      - kvPath: /oracle/data/dev/creds/veilarbdialog_q1-user
        mountPath: /var/run/secrets/nais.io/oracle_creds
      - kvPath: /oracle/data/dev/config/veilarbdialog_q1
        mountPath: /var/run/secrets/nais.io/oracle_config
      - kvPath: /serviceuser/data/dev/srvveilarbdialog
        mountPath: /secrets/serviceuser
      - kvPath: /kv/preprod/fss/veilarbdialog/q1
        mountPath: /var/run/secrets/nais.io/vault
  webproxy: true
  secureLogs:
    enabled: true
  kafka:
    pool: nav-dev
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
      allowAllUsers: true #todo burde vi legge inn noen roller her?
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    inbound:
      rules:
        - application: veilarbapi
          namespace: pto
          cluster: dev-gcp
        - application: veilarbpersonflate
          namespace: poao
          cluster: dev-gcp
        - application: mulighetsrommet-api
          namespace: team-mulighetsrommet
          cluster: dev-gcp
        - application: veilarbdirigent
          namespace: pto
          cluster: dev-fss
        - application: aktivitetsplan
          namespace: pto
          cluster: dev-gcp
        - application: arbeidsrettet-dialog
          namespace: pto
          cluster: dev-gcp
        - application: aia-backend
          namespace: paw
          cluster: dev-gcp
        - application: start-samtale
          namespace: pto
          cluster: dev-gcp
  env:
    - name: APP_ENVIRONMENT_NAME
      value: q1
    - name: APP_CLUSTER_NAME
      value: dev-fss
    - name: DIALOG_EKSTERN_URL
      value: https://pto.dev.ekstern.nav.no/arbeid/dialog
    - name: APPD_ENABLED
      value: "false"
