kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarbdialog
  namespace: pto
  cluster: prod-fss
  labels:
    team: pto
spec:
  image: ghcr.io/navikt/veilarbdialog/veilarbdialog:{{version}}
  port: 8080
  prometheus:
    enabled: true
    path: /veilarbdialog/internal/prometheus
  liveness:
    path: /veilarbdialog/internal/info
    port: 8080
    initialDelay: 30
  readiness:
    path: /veilarbdialog/internal/info
    port: 8080
    initialDelay: 30
  replicas:
    min: 4
    max: 8
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "2"
      memory: 8092Mi
    requests:
      cpu: "1"
      memory: 1536Mi
  ingresses:
    - https://veilarbdialog.nais.adeo.no
    - https://app.adeo.no/veilarbdialog
    - https://veilarbdialog.prod-fss-pub.nais.io
  envFrom:
    - configmap: pto-config
  vault:
    enabled: true
    paths:
      - kvPath: /oracle/data/prod/creds/veilarbdialog-user
        mountPath: /var/run/secrets/nais.io/oracle_creds
      - kvPath: /oracle/data/prod/config/veilarbdialog
        mountPath: /var/run/secrets/nais.io/oracle_config
      - kvPath: /serviceuser/data/prod/srvveilarbdialog
        mountPath: /secrets/serviceuser
      - kvPath: /kv/prod/fss/veilarbdialog/default
        mountPath: /var/run/secrets/nais.io/vault
  webproxy: true
  secureLogs:
    enabled: true
  kafka:
    pool: nav-prod
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
      allowAllUsers: true #todo burde vi legge inn noen roller her?
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    inbound:
      rules:
        - application: veilarbapi
          namespace: pto
          cluster: prod-gcp
        - application: veilarbpersonflate
          namespace: poao
          cluster: prod-gcp
        - application: mulighetsrommet-api
          namespace: team-mulighetsrommet
          cluster: prod-gcp
        - application: veilarbdirigent
          namespace: pto
          cluster: prod-fss
        - application: aktivitetsplan
          namespace: pto
          cluster: prod-gcp
        - application: arbeidsrettet-dialog
          namespace: pto
          cluster: prod-gcp
        - application: aia-backend
          namespace: paw
          cluster: prod-gcp
        - application: start-samtale
          namespace: pto
          cluster: prod-gcp
  env:
    - name: APP_ENVIRONMENT_NAME
      value: p
    - name: APP_CLUSTER_NAME
      value: prod-fss
    - name: DIALOG_EKSTERN_URL
      value: https://www.nav.no/arbeid/dialog
