apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: veilarbdialog
  namespace: dab
  cluster: dev-gcp
  labels:
    team: dab
spec:
  unleashInstance:
    apiVersion: unleash.nais.io/v1
    kind: RemoteUnleash
    name: dab
  secretName: veilarbdialog-unleash-api-token
  environment: development
