apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: veilarbdialog
  namespace: pto
  cluster: dev-fss
  labels:
    team: pto
spec:
  unleashInstance:
    apiVersion: unleash.nais.io/v1
    kind: RemoteUnleash
    name: dab
  secretName: veilarbdialog-unleash-api-token
  environment: development
