create table DIALOG_AKTOR (
  AKTOR_ID VARCHAR(255) NOT NULL,
  SISTE_ENDRING TIMESTAMP(6),
  TIDSPUNKT_ELDSTE_VENTENDE TIMESTAMP(6),
  TIDSPUNKT_ELDSTE_UBEHANDLEDE TIMESTAMP(6)
);

CREATE INDEX DIALOG_METADATA_IDX ON DIALOG_AKTOR (SISTE_ENDRING);
