ALTER TABLE DIALOG_AKTOR ADD OPPRETTET_TIDSPUNKT TIMESTAMP;
UPDATE DIALOG_AKTOR set OPPRETTET_TIDSPUNKT = SISTE_ENDRING;

ALTER TABLE DIALOG_AKTOR MODIFY OPPRETTET_TIDSPUNKT TIMESTAMP NOT NULL;

DROP INDEX DIALOG_METADATA_IDX;
CREATE INDEX DIALOG_METADATA_IDX ON DIALOG_AKTOR (OPPRETTET_TIDSPUNKT);
