ALTER TABLE DIALOG ADD lest_av_bruker timestamp;
ALTER TABLE DIALOG ADD lest_av_veileder timestamp;
ALTER TABLE DIALOG ADD aktivitet_id VARCHAR(64);

ALTER TABLE DIALOG ADD CONSTRAINT unique_aktivitet_id UNIQUE(aktivitet_id);

ALTER TABLE HENVENDELSE ADD avsender_type VARCHAR(64) NOT NULL;
ALTER TABLE HENVENDELSE ADD avsender_id VARCHAR(64) NOT NULL;
