create table BRUKERNOTIFIKASJON
(
    ID                       NUMBER(19) generated by default as identity primary key,
    EVENT_ID                 VARCHAR(40)              not null,
    DIALOG_ID                NUMBER(19)                not null,
    FOEDSELSNUMMER           VARCHAR(255)              not null,
    OPPFOLGINGSPERIODE_ID    VARCHAR(255)              not null,
    TYPE                     VARCHAR(255)              not null,
    STATUS                   VARCHAR(255)              not null,
    OPPRETTET                TIMESTAMP                 not null,
    MELDING                  VARCHAR(500)              not null,
    VARSEL_FEILET            TIMESTAMP,
    AVSLUTTET                TIMESTAMP,
    BEKREFTET_SENDT          TIMESTAMP,
    FORSOKT_SENDT            TIMESTAMP,
    FERDIG_BEHANDLET         TIMESTAMP,
    VARSEL_KVITTERING_STATUS VARCHAR(255) default NULL not null,
    SMSTEKST                 VARCHAR2(160),
    EPOSTTITTEL              VARCHAR2(200),
    EPOSTBODY                VARCHAR2(3000),
    constraint BRUKERNOTIFIKASJON_FK
        foreign key (DIALOG_ID) references DIALOG (DIALOG_ID)
);

create index BRUKERNOTIFIKASJON_STATUS_IDX
    on BRUKERNOTIFIKASJON (STATUS);