CREATE TABLE FEILEDE_KAFKA_MELDINGER (
    AKTOR_ID VARCHAR(255) NOT NULL,
    TIDSPUNKT_ELDSTE_VENTENDE TIMESTAMP(6),
    TIDSPUNKT_ELDSTE_UBEHANDLEDE TIMESTAMP(6),
    OPPRETTET_TIDSPUNKT TIMESTAMP NOT NULL
)