CREATE TABLE KLADD (
    AKTOR_ID VARCHAR(255) NOT NULL,
    DIALOG_ID number(19, 0),
    AKTIVITET_ID VARCHAR(64),
    OVERSKRIFT varchar(255),
    TEKST CLOB,
    LAGT_INN_AV VARCHAR(64) NOT NULL,
    OPPDATERT TIMESTAMP,
    OPPRETTET TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    constraint KLADD_PK primary key (AKTIVITET_ID, DIALOG_ID, AKTOR_ID, LAGT_INN_AV)
)