create table brukernotifikasjon
(
    id                              number(19) generated by default as identity primary key,
    brukernotifikasjon_id           varchar(255) not null,
    dialog_id                    number(19) not null,
    foedselsnummer                  varchar(255) not null,
    oppfolgingsperiode              varchar(255) not null,
    type                            varchar(255) not null,
    status                          varchar(255) not null,
    sendt                           timestamp    not null,
    melding                         varchar(500) not null,
    varsel_feilet                   timestamp,
    avsluttet                       timestamp,
    CONSTRAINT brukernotifikasjon_FK FOREIGN KEY (dialog_id) REFERENCES DIALOG (aktivitet_id)
);