CREATE TABLE ESKALERINGSVARSEL
(
    id                    number generated by default as identity primary key,
    aktor_id              NVARCHAR2(255) NOT NULL,
    opprettet_av          NVARCHAR2(255) NOT NULL,
    opprettet_dato        TIMESTAMP      NOT NULL,
    tilhorende_dialog_id  NUMBER(19)     NOT NULL,
    opprettet_begrunnelse CLOB,
    avsluttet_dato        TIMESTAMP,
    avsluttet_av          NVARCHAR2(255),
    avsluttet_begrunnelse CLOB,
    PRIMARY KEY (id)
);
