ktor:
  deployment:
    port: 8080
  application:
    modules:
      - no.nav.dialogvarsler.ApplicationKt.module

topic:
  ny-dialog: "$ny-dialog-topic:null"

kafka:
  brokers: "$KAFKA_BROKERS:null"
  truststore:
    path: "KAFKA_TRUSTSTORE_PATH:null"
    password: "KAFKA_CREDSTORE_PASSWORD:null"
  keystore:
    path: "KAFKA_KEYSTORE_PATH:null"
    password: "KAFKA_CREDSTORE_PASSWORD:null"

no:
  nav:
    security:
      jwt:
        issuers:
          - discoveryurl: "$AZURE_APP_WELL_KNOWN_URL:null"
            accepted_audience: "$AZURE_APP_CLIENT_ID:null"
            issuer_name: "AzureAD"