name: Deploy main-gcp to dev and prod
run-name: Deploy gcp-main by @${{ github.actor }}
on:
  push:
    branches:
      - gcp-main

permissions:
  contents: read
  packages: write

env:
  IMAGE_TAG: ${{ github.sha }}
  IMAGE: ghcr.io/${{ github.repository }}/veilarbdialog
  PRINT_PAYLOAD: true

concurrency:
  group: deploy_feature_branch
  cancel-in-progress: true

jobs:
  test-build-push:
    name: Test, build, push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'
      - name: Build maven artifacts
        run: mvn -B package -DskipTests
      - uses: docker/login-action@v2
        name: Docker login
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        name: Push image
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}:${{ env.IMAGE_TAG }}

  deploy-to-dev:
    name: Deploy to dev
    runs-on: ubuntu-latest
    needs: [test-build-push]
    steps:
      - name: Veilarbdialog - Deploy application to dev
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.DAB_NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/nais-dev-gcp.yaml
          VAR: version=${{ env.IMAGE_TAG }}

  deploy-to-prod:
    name: Deploy to prod
    runs-on: ubuntu-latest
    needs: [ deploy-to-dev ]
    steps:
      - name: Veilarbdialog - Deploy application
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.DAB_NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais/nais-prod-gcp.yaml
          VAR: version=${{ env.IMAGE_TAG }}
